/**
 * Entity types supported by the application
 */
export type EntityType = 'person' | 'organization' | 'location' | 'date' | 'other'

/**
 * Structure representing an extracted entity
 */
export interface Entity {
  id: string
  name: string
  type: EntityType
  aliases: string[]
  summary?: string  // Summary of the entity generated by DeepSeek (optional)
}

/**
 * Structure representing a relationship between entities
 */
export interface Relationship {
  id: string
  source: string
  target: string
  strength: number
}

/**
 * Result of entity extraction process containing entities and their relationships
 */
export interface ExtractionResult {
  entities: Entity[]
  relationships: Relationship[]
}

// The local entity extraction logic has been removed.
// These operations are now handled by the DeepSeek API through the API route. 